### PR TITLE
Ci docs and build

### PR DESCRIPTION
**Pull request by matthid**
See #3.

Things left to do:
 - Create AppVeyor and Travis accounts
 - Create a new orphan branch "gh-pages" and push it
 - Run `./build`, `./build GithubDoc_single` and `./build ReleaseGithubDoc_single` to generate and push the documentation (will look like http://matthid.github.io/ircdotnet/)
 - You can create the nuget package with `./build Release` or `./build NuGet_single`

Feel free to ask anything if you have problems. If you need help with the orphan branch you can use my `gh-pages` branch as well and push it to your repository. If there are problems you can add me as collaborator and I can setup the initial documentation branch (once its there the build script should work).

### CODE REVIEW

**Comment by alexreg** [comment]
This is great. Thanks for beginning work on this. I think I'll actually add you as collaborator to this project for now, so that you can create a new branch for this work, while leaving master stable and working. Then when we're sure this whole modernisation procedure is complete and tested, we can merge that branch into master. Sound fair?

**Comment by matthid** [comment]
Yeah thanks, but I think it should be working already. 

Just tell me when you have setup the accounts (travis, appveyor) we should see the builds starting immediately. As I opened the pull request against the devel branch (there is no `master` branch?) I think we can merge this (after the accounts are setup).

**Comment by matthid** [comment]
The docs are now available at https://alexreg.github.io/IrcDotNet/ (and the gh-pages branch is setup).

**Comment by alexreg** [comment]
Okay great. The image (in the top-right) isn't displaying for me on GitHub Page... is this meant to be the logo? Anyway, if you want a logo to put up, you can use the one from Launchpad maybe: https://launchpadlibrarian.net/38103098/Launchpad_Brand.png (or a better one if you like, as long as it's not copyrighted of course).

I'll set up the travis and appveyor accounts now. How do we need to configure them?

Finally, feel free to rename the devel branch to master now that everything is on GitHub.

**Comment by matthid** [comment]
Yeah the project logo is missing (but it can be easily added/changed later on).
You just need to create the accounts and link them with your github account, then you just need to enable the IrcDotNet project once it is listed. Nothing special is needed AFAIK.
OK I will create a master branch, when everything is green the first time :)

**Comment by alexreg** [comment]
Okay cool. I've set up the travis and appveyor accounts, so it should be good to go. Do we need to enable webhooks for either, or is that all done?

**Comment by matthid** [comment]
ah the builds are starting, cool :)

**Comment by alexreg** [comment]
Looks good! Are we still waiting for https://alexreg.github.io/IrcDotNet/ to update now?

**Comment by matthid** [comment]
That has to be done manually as I can't push the gh-pages branch from within travis or appveyor without adding any kind of password/secret to the repository (which isn't a good idea obviously). But `./build Release` will ask to update it, you can try it if you want.

**Comment by alexreg** [comment]
Okay. I don't see any ./build script in that branch. Are you sure you added & pushed it?

**Comment by alexreg** [comment]
I've renamed the devel branch to master, incidentally.

**Comment by alexreg** [comment]
Sorry, one more question: is there any way to view the current build/test results (state) from GitHub, or do I have to go onto travis and appveyor for that? (I know it shows the status of pull requests on GitHub.)

**Comment by matthid** [comment]
Ok one at a time:
With `build` I mean the `build.cmd` (windows) and `build.sh` (linux) in the root directory. You need to run them from the command line.

You can see the build status of all branches on: https://github.com/alexreg/IrcDotNet/branches

We can add build badges like https://github.com/Antaris/RazorEngine to the readme (scroll down to the readme) but I need the badge links: Copy one from https://ci.appveyor.com/project/alexreg/IrcDotNet/settings/badges (hope this link is correct, can't check as its your account).

Just copy one link an I will add the badges to the readme.

**Comment by alexreg** [comment]
Yes, I'm afraid I don't see either of those build files...

Anyway, here's the project status badge link (actually Markdown code):
````
[![Build status](https://ci.appveyor.com/api/projects/status/1kgumufg5xre9doo?svg=true)](https://ci.appveyor.com/project/alexreg/ircdotnet)
````

**Comment by matthid** [comment]
Yes exactly the link I need!

Did you checkout the latest changes?
`git fetch origin`
`git checkout -b master origin/master`

I would also suggest to add a `develop` branch and make it the default and merge to master only on releases (this way master is very stable and pull requests default to develop). I can only add the branch but marking a branch as default has to be done on the github settings. I would also suggest to add a documentation link (https://alexreg.github.io/IrcDotNet/) to the quick description (the description on top of the repository on github)

**Comment by matthid** [comment]
Ok the badges are now there. Maybe I can help you out with your git problems more interactively on IRC or IM?

**Comment by alexreg** [comment]
Sure, just ping me on IRC? I'm on right now.

The link has already been at the top of the page for an hour or so now. :)

**Comment by matthid** [comment]
Ah nice! I'm on #irc.net (and ##irc.net) channel on freenode.net via webchat.freenode.net and there is nobody there?

**Pull request merged**
