### PR TITLE
Latest changes from various repositories.

### PR DESCRIPTION
**Pull request by matthid**
This pull request includes the latest changes from various developers here on github merged into a single branch.
It's based on the latest official source I could find (http://bazaar.launchpad.net/~ircdotnet-dev/ircdotnet/0.4/revision/49).
Finally I rebased several old bugfixes which never made it into the codebase.

### CODE REVIEW

**Comment by alexreg** [comment]
Many thanks! A lot of these fixes were much needed, I admit. I just haven't worked with .NET for some time, so never got around to fixing them.

Which of the bugs listed at https://bugs.launchpad.net/ircdotnet did you end up fixing, incidentally?

**Comment by matthid** [comment]
Good question, at least https://bugs.launchpad.net/ircdotnet/+bug/862420 should be fixed now, but I can't give you a complete list as not all commits are mine...

**Comment by alexreg** [comment]
Okay, good to know. I’ll take a look at the others quickly and update their statuses. I’m officially migrating the project over to GitHub now in any case, since Launchpad is dying a slow death, but the Launchpad Bugs page will still be used for those outstanding issues.

**Comment by matthid** [comment]
Nice to hear, thanks!

**Comment by matthid** [comment]
After a quick look over the issues I think https://bugs.launchpad.net/ircdotnet/+bug/1254113 is fixed as well.

**Pull request merged**
